/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StringCalculator;


public class StringCalculator {

    public int add(String s) {
        if(s.isEmpty()) {
            return 0;
        }

        int result = 0;
        String delimiter = ",|\n";

        if(s.startsWith("//")) {
            delimiter = s.substring(2,3);
            s = s.substring(4);
        }

        for(String operand : s.split(delimiter)) {
            result += Integer.parseInt(operand);
        }

        return result;
    }
}
