/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StringCalculator;


import java.security.InvalidParameterException;

public class StringCalculator {

    private final String ERROR_MESSAGE = "negatives not allowed";

    public int add(String s) throws InvalidParameterException {
        if(s.isEmpty()) {
            return 0;
        }

        int result = 0;

        String expression = s.startsWith("//") ? s.substring(4) : s;
        String delimiter = getDelimiter(s);

        String errorMessage = "";
        for(String operand : expression.split(delimiter)) {
            if(Integer.parseInt(operand) < 0) {
                errorMessage = errorMessage.concat(" " + operand);
            }
            if(Integer.parseInt(operand) <= 1000) {
                result += Integer.parseInt(operand);
            }
        }

        if(errorMessage.length() > 0) {
            throw new InvalidParameterException(ERROR_MESSAGE + errorMessage);
        }

        return result;
    }

    private String getDelimiter(String s) {
        return s.startsWith("//") ? s.substring(2,3) : ",|\n";
    }
}
