/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StringCalculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class StringCalculatorTests {
    @Test public void AddGivenEmptyStringReturnsZero() {
        StringCalculator calculator = new StringCalculator();
        int result = calculator.add("");
        assertEquals(0, result);
    }
}
